springdoc:
  swagger-ui:
    path: /
spring:
  profiles:
    include: db, oauth2
  data:
    web:
      pageable:
        one-indexed-parameters: true
#logging:
#  config: classpath:logback-spring.xml